sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
env:
    - EMBER_VERSION=2.13
cache:
  directories:
    - "node_modules"
matrix:
  fast_finish: true
  # allow_failures:
  #   - env: EMBER_VERSION=2.13

before_install:
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm config set spin false
    - npm install -g npm
    - npm install -g ember-cli@2.13
    - npm install -g phantomjs-prebuilt
    - npm install -g bower
    - node --version
    - bower --version
    - ember -v

install:
    - bower install
    - npm install
script:
    - ember t