os: linux
dist: trusty
group: stable
sudo: required
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
language: node_js
node_js:
  - "8.11.2"
before_install:
    - export DISPLAY=':99.0'
    - sh -e /etc/init.d/xvfb start
    - npm config set spin false
    - npm install -g ember-cli@2.13.0
    - npm install -g bower
install:
    - bower install
    - npm install
script:
    - ember test