os: linux
dist: trusty
group: stable
sudo: required
language: node_js
node_js:
  - "8.9.4"
branches:
  only:
    - "master"
cache:
  directories:
    - "node_modules"
before_install:
    - npm install -g ember-cli@2.13.0
    - npm install phantomjs-prebuilt
    - npm install -g bower
install:
    - bower install
    - npm install
script:
    - ember test