os: linux
dist: trusty
group: stable
sudo: false
language: node_js
node_js:
  - "8.9.4"
env:
  - EMBER_TRY_SCENARIO=ember-lts-2.13.0,
cache:
  directories:
    - "node_modules"
before_install:
    - npm config set spin false
    - npm install -g bower
    - bower --version
    - npm install phantomjs-prebuilt
    - node_modules/phantomjs-prebuilt/bin/phantomjs --version
    - npm install -g ember-cli@2.13.0
install:
    - npm install
    - bower install
script:
    - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup